// Brazilian States with IBGE codes
export const BRAZILIAN_STATES = [
  { id: 'AC', name: 'Acre' },
  { id: 'AL', name: 'Alagoas' },
  { id: 'AP', name: 'Amapá' },
  { id: 'AM', name: 'Amazonas' },
  { id: 'BA', name: 'Bahia' },
  { id: 'CE', name: 'Ceará' },
  { id: 'DF', name: 'Distrito Federal' },
  { id: 'ES', name: 'Espírito Santo' },
  { id: 'GO', name: 'Goiás' },
  { id: 'MA', name: 'Maranhão' },
  { id: 'MT', name: 'Mato Grosso' },
  { id: 'MS', name: 'Mato Grosso do Sul' },
  { id: 'MG', name: 'Minas Gerais' },
  { id: 'PA', name: 'Pará' },
  { id: 'PB', name: 'Paraíba' },
  { id: 'PR', name: 'Paraná' },
  { id: 'PE', name: 'Pernambuco' },
  { id: 'PI', name: 'Piauí' },
  { id: 'RJ', name: 'Rio de Janeiro' },
  { id: 'RN', name: 'Rio Grande do Norte' },
  { id: 'RS', name: 'Rio Grande do Sul' },
  { id: 'RO', name: 'Rondônia' },
  { id: 'RR', name: 'Roraima' },
  { id: 'SC', name: 'Santa Catarina' },
  { id: 'SP', name: 'São Paulo' },
  { id: 'SE', name: 'Sergipe' },
  { id: 'TO', name: 'Tocantins' },
] as const;

// Popular CNAE codes for lead generation
export const CNAE_CATEGORIES = [
  { code: '5611201', label: 'Restaurantes e similares' },
  { code: '5611203', label: 'Lanchonetes e casas de sucos' },
  { code: '5611204', label: 'Bares e similares' },
  { code: '5612100', label: 'Serviços de alimentação' },
  { code: '8630503', label: 'Clínicas médicas' },
  { code: '8630504', label: 'Clínicas odontológicas' },
  { code: '8650001', label: 'Psicologia e psicanálise' },
  { code: '8650003', label: 'Fonoaudiologia' },
  { code: '8650004', label: 'Fisioterapia' },
  { code: '8650006', label: 'Nutrição' },
  { code: '9313100', label: 'Academias de ginástica' },
  { code: '9602501', label: 'Salões de beleza' },
  { code: '9602502', label: 'Barbearias' },
  { code: '4781400', label: 'Lojas de vestuário' },
  { code: '4782201', label: 'Calçados' },
  { code: '4789001', label: 'Joalherias e relojoarias' },
  { code: '6810201', label: 'Imobiliárias' },
  { code: '6810202', label: 'Corretoras de imóveis' },
  { code: '4511101', label: 'Concessionárias de veículos' },
  { code: '4520001', label: 'Oficinas mecânicas' },
  { code: '4520002', label: 'Serviços de lanternagem' },
  { code: '4520005', label: 'Serviços de lavagem de veículos' },
  { code: '8531700', label: 'Escolas de ensino fundamental' },
  { code: '8599601', label: 'Cursos de idiomas' },
  { code: '8599603', label: 'Cursos preparatórios' },
  { code: '8599604', label: 'Cursos profissionalizantes' },
  { code: '5510801', label: 'Hotéis' },
  { code: '5590601', label: 'Pousadas' },
  { code: '5590602', label: 'Motéis' },
  { code: '4771701', label: 'Farmácias' },
  { code: '4771702', label: 'Farmácias de manipulação' },
  { code: '4772500', label: 'Cosméticos e perfumaria' },
  { code: '4763601', label: 'Lojas de brinquedos' },
  { code: '4763602', label: 'Papelarias' },
  { code: '4753900', label: 'Tapetes e cortinas' },
  { code: '4754701', label: 'Móveis' },
  { code: '4756300', label: 'Instrumentos musicais' },
  { code: '4759899', label: 'Outros artigos de uso doméstico' },
  { code: '4744001', label: 'Materiais de construção' },
  { code: '4744099', label: 'Ferragens e ferramentas' },
  { code: '9001901', label: 'Produção teatral' },
  { code: '9001902', label: 'Produção musical' },
  { code: '9001903', label: 'Produção de shows' },
  { code: '9002701', label: 'Estúdios de gravação' },
  { code: '9311500', label: 'Clubes esportivos' },
  { code: '9319101', label: 'Produção de eventos esportivos' },
  { code: '9329801', label: 'Discotecas e casas de shows' },
  { code: '6201501', label: 'Desenvolvimento de software' },
  { code: '6202300', label: 'Consultoria em TI' },
  { code: '6203100', label: 'Suporte técnico em TI' },
  { code: '6311900', label: 'Data centers' },
  { code: '6319400', label: 'Portais e hospedagem' },
  { code: '7311400', label: 'Agências de publicidade' },
  { code: '7319002', label: 'Marketing direto' },
  { code: '7410202', label: 'Design de interiores' },
  { code: '7410203', label: 'Design de produto' },
  { code: '7420001', label: 'Estúdios fotográficos' },
  { code: '7420004', label: 'Filmagem de eventos' },
  { code: '6911701', label: 'Escritórios de advocacia' },
  { code: '6920601', label: 'Contabilidade' },
  { code: '6920602', label: 'Auditoria' },
] as const;

export type BrazilianState = typeof BRAZILIAN_STATES[number];
export type CNAECategory = typeof CNAE_CATEGORIES[number];
