-- Add transcription column to inbox_messages
ALTER TABLE public.inbox_messages 
ADD COLUMN IF NOT EXISTS transcription TEXT NULL;

-- Add comment
COMMENT ON COLUMN public.inbox_messages.transcription IS 'Audio transcription text generated by AI';